version: "3.1"
services:
    database:
        image: postgres:12
        ports: 
            - 5432:5432
        volumes:
            - database-data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}

volumes:
    database-data: